name       : solus-sc
version    : '23'
release    : 48
source     :
    - git|https://github.com/getsolus/solus-sc.git : 2d9b1e5c606e307c8c00d423556da725c6e4a0da
license    : GPL-2.0-only
component  : desktop
summary    : Solus Software Center
description: |
    Solus Software Center
builddeps  :
    - python-distutils-extra
rundeps    :
    - appstream-glib
    - appstream-data
    - at-spi2-atk
    - gvfs
    - libgtk-3
    - python-gobject
    - solus-sc-icons
replaces   :
    - evolve-sc
build      : |
    %python_setup
install    : |
    %python_install
