name       : solus-sc
version    : '20'
release    : 26
source     :
    - https://github.com/solus-project/solus-sc/archive/v20.tar.gz : 6f0c48f9e531b1a51aedb5a262694c048a619db7fe7326034176e1abb25e9343
license    : GPL-2.0
component  : desktop
summary    : Solus Software Center
description: |
    Solus Software Center
builddeps  :
    - python-distutils-extra
rundeps    :
    - python-gobject
    - libgtk-3
    - appstream-glib
    - appstream-data
replaces   :
    - evolve-sc
build      : |
    %python_setup
install    : |
    %python_install
