name       : solus-sc
version    : '23'
release    : 47
source     :
    - git|https://github.com/getsolus/solus-sc.git : cbab7e083df75977bbaa2f01a42f89ae4a3b1477
license    : GPL-2.0-only
component  : desktop
summary    : Solus Software Center
description: |
    Solus Software Center
builddeps  :
    - python-distutils-extra
rundeps    :
    - appstream-glib
    - appstream-data
    - at-spi2-atk
    - gvfs
    - libgtk-3
    - python-gobject
    - solus-sc-icons
replaces   :
    - evolve-sc
build      : |
    %python_setup
install    : |
    %python_install
