name       : solus-sc
version    : '21'
release    : 32
source     :
    - https://github.com/getsolus/solus-sc/archive/v21.tar.gz : fd5c31d906a257b81ed56815b192c158fcaeeffa7450859c9e03bd89154701cf
license    : GPL-2.0
component  : desktop
summary    : Solus Software Center
description: |
    Solus Software Center
builddeps  :
    - python-distutils-extra
rundeps    :
    - appstream-glib
    - appstream-data
    - at-spi2-atk
    - gvfs
    - libgtk-3
    - python-gobject
replaces   :
    - evolve-sc
build      : |
    %python_setup
install    : |
    %python_install
