name       : solus-sc
version    : '22'
release    : 37
source     :
    - https://github.com/getsolus/solus-sc/archive/v22.tar.gz : c4e4950595be5e0b1ab0bbf7bed8fdc635635b4db1558bb298912821ac7a61fb
license    : GPL-2.0
component  : desktop
summary    : Solus Software Center
description: |
    Solus Software Center
builddeps  :
    - python-distutils-extra
rundeps    :
    - appstream-glib
    - appstream-data
    - at-spi2-atk
    - gvfs
    - libgtk-3
    - python-gobject
    - solus-sc-icons
replaces   :
    - evolve-sc
setup      : |
    %patch -p1 < $pkgfiles/0001-Add-a-desktop-action-for-going-to-the-Updates-view.patch
build      : |
    %python_setup
install    : |
    %python_install
