name       : solus-sc
version    : 15
release    : 16
source     :
    - https://github.com/solus-project/solus-sc/archive/v15.tar.gz : f03636510fc5ba910325d861bad7d77be7cab8710c04b9d3958700e8fc692c78
license    : GPL-2.0
component  : desktop.budgie
summary    : Solus Software Center
description: |
    Solus Software Center
builddeps  :
    - python-distutils-extra
rundeps    :
    - python-gobject
    - libgtk-3
    - appstream-glib
    - appstream-data
replaces   :
    - evolve-sc
build      : |
    %python_setup
install    : |
    %python_install
