name       : solus-sc
version    : '19'
release    : 22
source     :
    - https://github.com/solus-project/solus-sc/releases/download/v19/solus-sc-19.tar.gz : ba54544c0a10e0826065d0a8917fd3bc2bfdac33f8744b96d3031c36d9662969
license    : GPL-2.0
component  : desktop
summary    : Solus Software Center
description: |
    Solus Software Center
builddeps  :
    - python-distutils-extra
rundeps    :
    - python-gobject
    - libgtk-3
    - appstream-glib
    - appstream-data
replaces   :
    - evolve-sc
build      : |
    %python_setup
install    : |
    %python_install
