name       : solus-sc
version    : 16
release    : 19
source     :
    - https://github.com/solus-project/solus-sc/archive/v16.tar.gz : 5eb66e541a0652f1cb571981edc732e3a6c5e268f6a0dd88468a3a0492bd79d7
license    : GPL-2.0
component  : desktop
summary    : Solus Software Center
description: |
    Solus Software Center
builddeps  :
    - python-distutils-extra
rundeps    :
    - python-gobject
    - libgtk-3
    - appstream-glib
    - appstream-data
replaces   :
    - evolve-sc
setup      : |
    %patch -p1 < $pkgfiles/0006-Drop-TeamSpeak3-from-Third-Party.-It-ll-be-in-the-re.patch
    %patch -p1 < $pkgfiles/0007-Fix-T2697-action_show_updates-takes-no-extra-paramet.patch
    %patch -p1 < $pkgfiles/0008-Added-Webstorm-correctly-this-time-66.patch
build      : |
    %python_setup
install    : |
    %python_install
