name       : solus-sc
version    : 12.0
release    : 1
source     :
    - https://github.com/solus-project/solus-sc/archive/v12.0.tar.gz : 45ceff495c5873b95e8b0c16fea4638f0c09723d2e34d1c658fe399c697a21b0
license    : GPL-2.0
component  : desktop.budgie
summary    : Solus Software Center
description: |
    Solus Software Center
builddeps  :
    - python-distutils-extra
rundeps    :
    - python-gobject
    - libgtk-3
    - appstream-glib
replaces   :
    - evolve-sc
build      : |
    python setup.py build
install    : |
    python setup.py install --root="$installdir"
