name       : solus-sc
version    : '21'
release    : 33
source     :
    - git|https://github.com/getsolus/solus-sc.git : 1a39b57722f7c197eb7d0f0540863b8c08a43b3f
license    : GPL-2.0
component  : desktop
summary    : Solus Software Center
description: |
    Solus Software Center
builddeps  :
    - python-distutils-extra
rundeps    :
    - appstream-glib
    - appstream-data
    - at-spi2-atk
    - gvfs
    - libgtk-3
    - python-gobject
replaces   :
    - evolve-sc
build      : |
    %python_setup
install    : |
    %python_install
