name       : solus-sc
version    : 12.9
release    : 10
source     :
    - https://github.com/solus-project/solus-sc/releases/download/v12.9/solus-sc-12.9.tar.gz : e2d2b9c91be680dbc1781f894de5660dbb751f62d607bb1b8d4c747fd30a5063
license    : GPL-2.0
component  : desktop.budgie
summary    : Solus Software Center
description: |
    Solus Software Center
builddeps  :
    - python-distutils-extra
rundeps    :
    - python-gobject
    - libgtk-3
    - appstream-glib
    - appstream-data
replaces   :
    - evolve-sc
build      : |
    %python_setup
install    : |
    %python_install
