name       : solus-sc
version    : '19'
release    : 24
source     :
    - https://github.com/solus-project/solus-sc/releases/download/v19/solus-sc-19.tar.gz : ba54544c0a10e0826065d0a8917fd3bc2bfdac33f8744b96d3031c36d9662969
license    : GPL-2.0
component  : desktop
summary    : Solus Software Center
description: |
    Solus Software Center
builddeps  :
    - python-distutils-extra
rundeps    :
    - python-gobject
    - libgtk-3
    - appstream-glib
    - appstream-data
replaces   :
    - evolve-sc
setup      : |
    %patch -p1 < $pkgfiles/0001-changelog-Don-t-link-differential-IDs-that-s-just-si.patch
    %patch -p1 < $pkgfiles/0002-changelog-Don-t-swallow-greedily-and-add-bolding-sup.patch
    %patch -p1 < $pkgfiles/0003-changelog-Simplify-bug-cve-match-to-not-be-greedy.patch
build      : |
    %python_setup
install    : |
    %python_install
