name       : solus-sc
version    : '18'
release    : 21
source     :
    - https://github.com/solus-project/solus-sc/releases/download/v18/solus-sc-18.tar.gz : 71c3769a579ad5951382e457c0aedc8231c96124d1c9d661b526d8b2b3bc4be2
license    : GPL-2.0
component  : desktop
summary    : Solus Software Center
description: |
    Solus Software Center
builddeps  :
    - python-distutils-extra
rundeps    :
    - python-gobject
    - libgtk-3
    - appstream-glib
    - appstream-data
replaces   :
    - evolve-sc
build      : |
    %python_setup
install    : |
    %python_install
