name       : solus-sc
version    : 12.1
release    : 9
source     :
    - https://github.com/solus-project/solus-sc/archive/v12.1.tar.gz : f7b2b95ee5fec2266f52c0a91f3443e7061de64eb7651b3e53716bb63d4c0123
license    : GPL-2.0
component  : desktop.budgie
summary    : Solus Software Center
description: |
    Solus Software Center
builddeps  :
    - python-distutils-extra
rundeps    :
    - python-gobject
    - libgtk-3
    - appstream-glib
    - appstream-data
replaces   :
    - evolve-sc
setup      : |
    %patch -p1 < $pkgfiles/0001-Remove-dead-desktop.games-component.patch
    %patch -p1 < $pkgfiles/0002-Rename-Network-Tools-to-Internet-Software.patch
    %patch -p1 < $pkgfiles/0003-Forcibly-lower-the-time-to-package-anything.patch
    %patch -p1 < $pkgfiles/0004-Support-opera-stable-in-Third-Party.patch
    %patch -p1 < $pkgfiles/0005-Implement-support-for-Google-Talk-Plugin.patch
    %patch -p1 < $pkgfiles/0006-Add-support-for-Sublime-Text.patch
    %patch -p1 < $pkgfiles/0001-Fix-styling-on-the-sidebar.patch
    %patch -p1 < $pkgfiles/0002-Hacky-Force-background-on-separator.patch
build      : |
    python setup.py build
install    : |
    python setup.py install --root="$installdir"
