name       : solus-sc
version    : 14
release    : 13
source     :
    - https://github.com/solus-project/solus-sc/releases/download/v14/solus-sc-14.0.tar.gz : 43762a0787b656dcc57e62066dc683a61b0f6fb99d2533f0d6aeb110206a7456
license    : GPL-2.0
component  : desktop.budgie
summary    : Solus Software Center
description: |
    Solus Software Center
builddeps  :
    - python-distutils-extra
rundeps    :
    - python-gobject
    - libgtk-3
    - appstream-glib
    - appstream-data
replaces   :
    - evolve-sc
build      : |
    %python_setup
install    : |
    %python_install
