name       : solus-sc
version    : '23'
release    : 43
source     :
    - git|https://github.com/getsolus/solus-sc.git : ddcbb75893b984fef1ecd4ac6ea3b2cdbe0e7c0b
license    : GPL-2.0
component  : desktop
summary    : Solus Software Center
description: |
    Solus Software Center
builddeps  :
    - python-distutils-extra
rundeps    :
    - appstream-glib
    - appstream-data
    - at-spi2-atk
    - gvfs
    - libgtk-3
    - python-gobject
    - solus-sc-icons
replaces   :
    - evolve-sc
build      : |
    %python_setup
install    : |
    %python_install
